### ISSUE TITLE
Pickling objects that are results of "get"

### ISSUE THREAD

**Issue by pcmoritz** [amplab/ray#331]
At the moment, this doesn't work:

```python
import ray
import cPickle
ray.services.start_ray_local()
cPickle.dumps(ray.get(ray.put(1)))
```

It fails with the following error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-922996db023e> in <module>()
----> 1 cPickle.dumps(ray.get(ray.put(1)))

/home/pcmoritz/anaconda/lib/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
     68     else:
     69         if base is self.__class__:
---> 70             raise TypeError, "can't pickle %s objects" % base.__name__
     71         state = base(self)
     72     args = (self.__class__, base, state)

TypeError: can't pickle PyCapsule objects
```

This should be fixed once we replace the current deallocation mechanism of Python objects that use data from the object store with a mechanism that uses weak references to tell when the reference count of an object goes to 0.

**Comment by robertnishihara** [comment]
This was fixed by #407. Instead of adding fields to the class, we deserialize numpy arrays using a given "base object" that holds the object ID that we call `ray.get` on.

```python
import pickle  # It also works with cloudpickle.
import numpy as np
import ray
ray.init(start_ray_local=True)

x = np.zeros(10)
xid = ray.put(x)
xnew = ray.get(xid)

s = pickle.dumps(xnew)
t = pickle.loads(s)
```

Note that `xnew.base` is a `ray.worker.ObjectFixture`, and `xnew.base.objectid` is a `ray.ObjectID`, but pickle and cloudpickle appear to not attempt to seralize `xnew.base`, so it works out. If you check `t.base` it is `None`.
